// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import SelectsController from "./selects_controller"
application.register("selects", SelectsController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TaskController from "./task_controller"
application.register("task", TaskController)
