# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: task_tracker_development

test:
  <<: *default
  database: task_tracker_test

production:
  <<: *default
  database: task_tracker_production
  # Add other production-specific configurations here.
